#!/bin/bash

echo "Setting up packages I always install..."
sudo dnf update --refresh
sudo dnf install google-chrome-stable gimp
sudo dnf install @lxde-desktop-environment
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
dnf check-update && sudo dnf install code # or code-insiders

KEY="# Timotej Default Setup from Github"

BASHRC=~/.bashrc

CNT=`grep -c "$KEY" $BASHRC`



MYDIR=`pwd`

echo "Setting up bash..."
if [ $CNT == 0 ]; then
	echo "$KEY" >> $BASHRC
	echo "source $MYDIR/bash/bashrc" >> $BASHRC
else
	echo "Seems like you already ran this on this pc because I can find $KEY in .bashrc"
	echo "If that's a mistake, then delete $KEY from .bashrc and rerun this script."
fi

echo "Setting up git..."
$MYDIR/git/git-setup

