#!/bin/bash

KEY="# Timotej Default Setup from Github"

BASHRC=~/.bashrc

CNT=`grep -c "$KEY" $BASHRC`



MYDIR=`pwd`

echo "Setting up bash..."
if [ $CNT == 0 ]; then
	echo "$KEY" >> $BASHRC
	echo "source $MYDIR/bash/bashrc" >> $BASHRC
else
	echo "Seems like you already ran this on this pc because I can find $KEY in .bashrc"
	echo "If that's a mistake, then delete $KEY from .bashrc and rerun this script."
fi

echo "Setting up git..."
$MYDIR/git/git-setup
