#!/bin/bash

KEY="# Timotej Default Setup from Github"

BASHRC=~/.bashrc

CNT=`grep -c "$KEY" $BASHRC`

if [ $CNT != 0 ]; then
	echo "Seems like you already ran this on this pc because I can find $KEY in .bashrc"
	echo "If that's a mistake, then delete $KEY from .bashrc."
	exit 0
fi


MYDIR=`pwd`

echo "$KEY" >> $BASHRC
echo "source $MYDIR/bash/bashrc" >> $BASHRC
