
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias more='less'

export TIMOTEJ_SETUP=1

_MY_NAME_=`echo "${BASH_SOURCE[@]}" | awk '{print $1}'`
_MY_ROOT_=`dirname $_MY_NAME_`/..

PATH=$PATH:${_MY_ROOT_}/git/

source ${_MY_ROOT_}/git/git-prompt.sh

PS1="[\[\e[1;35m\]\w\[\e[1;33m\]\$(__git_ps1)\[\e[m\]]$ "

